//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WshLst.MonoForAndroid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxDropDownItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int MvxHttpSource = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_menu_add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_edit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_save = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icontransparent = 2130837509;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int MvxBindableListItemTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040023
			public const int addEntry = 2130968611;
			
			// aapt resource value: 0x7f040021
			public const int addList = 2130968609;
			
			// aapt resource value: 0x7f040014
			public const int buttonAddPhoto = 2130968596;
			
			// aapt resource value: 0x7f040019
			public const int buttonCancel = 2130968601;
			
			// aapt resource value: 0x7f040015
			public const int buttonRemovePhoto = 2130968597;
			
			// aapt resource value: 0x7f04001a
			public const int buttonSave = 2130968602;
			
			// aapt resource value: 0x7f040009
			public const int buttonScanBarcode = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int checkLocation = 2130968591;
			
			// aapt resource value: 0x7f040003
			public const int checkSelected = 2130968579;
			
			// aapt resource value: 0x7f040013
			public const int imagePhoto = 2130968595;
			
			// aapt resource value: 0x7f04001b
			public const int labelDesc = 2130968603;
			
			// aapt resource value: 0x7f04001d
			public const int labelName = 2130968605;
			
			// aapt resource value: 0x7f04001f
			public const int labelNotes = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int labelStore = 2130968606;
			
			// aapt resource value: 0x7f040002
			public const int linearLayout1 = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int linearLayout2 = 2130968580;
			
			// aapt resource value: 0x7f040018
			public const int linearLayout3 = 2130968600;
			
			// aapt resource value: 0x7f040022
			public const int logout = 2130968610;
			
			// aapt resource value: 0x7f040020
			public const int mvxList = 2130968608;
			
			// aapt resource value: 0x7f040024
			public const int shareWishList = 2130968612;
			
			// aapt resource value: 0x7f04000b
			public const int tableLayout1 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int tableRow1 = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int text1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int text2 = 2130968584;
			
			// aapt resource value: 0x7f04001c
			public const int textDescription = 2130968604;
			
			// aapt resource value: 0x7f040006
			public const int textEmail = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int textName = 2130968581;
			
			// aapt resource value: 0x7f040017
			public const int textNotes = 2130968599;
			
			// aapt resource value: 0x7f040011
			public const int textPrice = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int textStore = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int textView1 = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int textView2 = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int textView3 = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int textView4 = 2130968594;
			
			// aapt resource value: 0x7f040016
			public const int textView5 = 2130968598;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItem_Contact = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem_Entry = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListItem_List = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItem_Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Page_EditEntryView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Page_EditWishListView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Page_EntryView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Page_LoginView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Page_ShareView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Page_WishListsView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Page_WishListView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SplashScreen = 2130903051;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int ListsView_Menu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ListView_Menu = 2131099649;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int MvxBindableListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			private Styleable()
			{
			}
		}
	}
}
